version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx  # Ensure logs are written

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./html:/usr/share/nginx/html

  logs:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:514/udp"
    volumes:
      - ./logs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf

