version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx  # Ensure logs are written
    networks:
      - graylog

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - graylog

  logs:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:514/udp"
    volumes:
      - ./logs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    networks:
      - graylog

  # MongoDB without authentication for simplicity
  mongodb:
    image: "mongo:6.0"  
    restart: "on-failure"
    networks:
      - graylog
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"
    command: ["--wiredTigerCacheSizeGB", "0.5"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 64000
        hard: 64000

  # DataNode configuration
  datanode:
    image: "graylog/graylog-datanode:6.1"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # Fixed password secret
      GRAYLOG_DATANODE_PASSWORD_SECRET: "somesecretpasswordpepper"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - graylog  
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    restart: "on-failure"
    depends_on:
      - mongodb

  # Graylog configuration
  graylog:
    hostname: "server"
    image: "graylog/graylog:6.1"
    depends_on:
      - mongodb
      - datanode
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      # Fixed password secret - must match datanode
      GRAYLOG_PASSWORD_SECRET: "somesecretpasswordpepper"
      # Default admin password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW UDP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    networks:
      - graylog
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
    restart: "on-failure"
    
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - graylog
    restart: "on-failure"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://0.0.0.0:5140"
        tag: "dvwa"

networks:
  graylog:
    driver: "bridge"

volumes:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data: